// <auto-generated />
using System;
using DataManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataManager.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200523143359_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("DataManager.Models.ActiveMails", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("subscriberchatID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("subscriberchatID");

                    b.ToTable("activemails");
                });

            modelBuilder.Entity("DataManager.Models.ReadMails", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("mailID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("receiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("sender")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("mailID");

                    b.ToTable("readmails");
                });

            modelBuilder.Entity("DataManager.Models.Subscribers", b =>
                {
                    b.Property<long>("chatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("mailprocess")
                        .HasColumnType("INTEGER");

                    b.HasKey("chatID");

                    b.ToTable("subscribers");
                });

            modelBuilder.Entity("DataManager.Models.ActiveMails", b =>
                {
                    b.HasOne("DataManager.Models.Subscribers", "subscriber")
                        .WithMany()
                        .HasForeignKey("subscriberchatID");
                });

            modelBuilder.Entity("DataManager.Models.ReadMails", b =>
                {
                    b.HasOne("DataManager.Models.ActiveMails", "mail")
                        .WithMany()
                        .HasForeignKey("mailID");
                });
#pragma warning restore 612, 618
        }
    }
}
